s3:
  raw_data_filename: raw_data.csv
process_data:
  cleaned_data_filename: final_data.csv
  clean_data:
    target: 'churn'
data_handling:
  process_data:
    raw_data_path: data/raw/raw_data.csv
    final_data_path: data/final/final_data.csv
modeling:
  X_train_filename: X_train.csv
  X_test_filename: X_test.csv
  y_train_filename: y_train.csv
  y_test_filename: y_test.csv
  model_filename: rf_model.pkl
  pred_result_filename: pred_result.csv
  model_eval_filename: model_evaluation.txt
  train_model:
    used_features: ['international_plan', 'voice_mail_plan', 'number_vmail_messages',
                    'total_day_minutes', 'total_eve_minutes', 'total_night_minutes',
                    'total_intl_minutes', 'total_intl_calls', 'customer_service_calls']
    target: 'churn'
    test_size: 0.2
    random_state: 42
  pred_one_record:
    columns: ['international_plan', 'voice_mail_plan', 'number_vmail_messages',
              'total_day_minutes', 'total_eve_minutes', 'total_night_minutes',
              'total_intl_minutes', 'total_intl_calls', 'customer_service_calls']